version: '3.1'

services:
  php:
    build: ./docker
    working_dir: /usr/src/app
    volumes: 
      - .:/usr/src/app
  nodejs:
    image: node
    working_dir: /usr/src/app
    volumes: 
      - .:/usr/src/app
